"""add unique constraint on social_accounts platform+external_id

Revision ID: 534034b26e3f
Revises: a0294bad56c8
Create Date: 2026-09-14 17:25:56.852553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534034b26e3f'
down_revision: Union[str, Sequence[str], None] = 'a0294bad56c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_social_accounts_platform_external_id', 'social_accounts', ['platform', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_social_accounts_platform_external_id', 'social_accounts', type_='unique')
    # ### end Alembic commands ###
