"""add subtitle_font to clip_jobs

Revision ID: b3978b1a4c41
Revises: 46cc054667e3
Create Date: 2026-09-17 05:56:51.687304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3978b1a4c41'
down_revision: Union[str, Sequence[str], None] = '46cc054667e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'clip_jobs',
        sa.Column('subtitle_font', sa.String(length=50), nullable=False, server_default='anton'),
    )
    op.alter_column('clip_jobs', 'subtitle_font', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clip_jobs', 'subtitle_font')
    # ### end Alembic commands ###
