"""add music_path to video_ai_jobs

Revision ID: b3ed8ab7f4d1
Revises: b3978b1a4c41
Create Date: 2026-09-17 06:07:53.866621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ed8ab7f4d1'
down_revision: Union[str, Sequence[str], None] = 'b3978b1a4c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_ai_jobs', sa.Column('music_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_ai_jobs', 'music_path')
    # ### end Alembic commands ###
